// user actions
export const ADD_USER = "ADD_USER";
export const EDIT_USER = "EDIT_USER";
export const REMOVE_USER = "REMOVE_USER";
// usages
export const ADD_USAGE = "ADD_USAGE";
// payment
export const ADD_PAYMENT = "ADD_PAYMENT";

// user filter actions
export const SET_USER_TEXT_FILTER = "SET_USER_TEXT_FILTER";
export const SET_CONTACT_NUMBER_FILTER = "SET_CONTACT_NUMBER_FILTER";
export const SET_EMAIL_ID_FILTER = "SET_EMAIL_ID_FILTER";
export const SET_CURRENT_PLAN_ID_FILTER = "SET_CURRENT_PLAN_ID_FILTER";
export const SET_USER_ACCOUNT_STATUS_FILTER = "SET_USER_ACCOUNT_STATUS_FILTER";
export const SET_IS_DUE_FILTER = "SET_IS_DUE_FILTER";
export const SET_SORT_BY_FILTER = "SET_SORT_BY_FILTER";
export const SET_USER_START_DATE_FILTER = "SET_USER_START_DATE_FILTER";
export const SET_USER_END_DATE_FILTER = "SET_USER_END_DATE_FILTER";

// plan action
export const ADD_PLAN = "ADD_PLAN";
export const EDIT_PLAN = "EDIT_PLAN";
export const REMOVE_PLAN = "REMOVE_PLAN";

// plan filter action
export const SET_PLAN_TEXT_FILTER = "SET_PLAN_TEXT_FILTER";
export const SET_PRICE_FILTER = "SET_PRICE_FILTER";
export const SET_PLAN_STATUS_FILTER = "SET_PLAN_STATUS_FILTER";
export const SET_VALIDITY_PERIOD_FILTER = "SET_VALIDITY_PERIOD_FILTER";
export const SET_PLAN_START_DATE_FILTER = "SET_PLAN_START_DATE_FILTER";
export const SET_PLAN_END_DATE_FILTER = "SET_PLAN_END_DATE_FILTER";
export const SET_PLAN_SORT_BY_FILTER = "SET_PLAN_SORT_BY_FILTER";
